- name: Install Design tools
  community.general.homebrew:
    name:
      - darktable
      - drawio
      - figma
      - gimp
      - affinity-photo
      - affinity-designer
    state: present
  when: ansible_os_family == "Darwin"
