- name: Install VSCode, iterm2, Chrome and Insomnia
  community.general.homebrew:
    name:
      - visual-studio-code
      - insomnia
      - google-chrome
    state: present
  when: ansible_os_family == "Darwin"
